kubeconfig: ./examples/config-k8s.fake
in_template: ./examples/haproxy.tmpl
out_file: /tmp/haproxy.actual
interval: 7s
health_check_port: 8099
hooks:
  post_render:
    - "/bin/echo"
    - "Hello World !"